const language = {
  en: {
    firstName: 'first',
    lastName: 'last',
    patronymic: 'patr',
    desc: 'Description',
    'al-1': 'She began to act as a singer in the troupe of the Main Front Political Theater of the Western Front.',
    'al-2': 'Start learning in the Minsk Music College.',
    'al-3': 'She performed Belarusian folk songs at the International Music Fair in Frankfurt am Main (Germany).',
    'al-4': 'The end of training in the Minsk musical technical school. Training in a special opera class.',
    'al-5': 'Soloist of the Belarusian Opera and Ballet Theater in Minsk. She performed both soprano and mezzo-soprano parts.',
    'al-6': 'The start of the career of the main director at the Belarusian Opera and Ballet Theater.',
    'al-7': 'The end of the career of the main director in the Belarusian Theater of Opera and Ballet.',
    'bn-1': 'together with his daughters Vanda and Elena, as well as with his close friends, he created an amateur troupe in the Polivachi farm.',
    'bn-2': 'on the basis of the amateur group, a permanent group was formed and a long tour began in Belarus.',
    'bn-3': 'organized the Prozoroki Belarusian Credit Society, in which every peasant could receive a loan at a small percentage.',
    'bn-4': "began to take an active part in the activities of the Vilnius society 'To help the front' ",
    'bn-5': "finished taking an active part in the activities of the Vilnius society 'To help the front' ",
    'bn-6': 'went to the Western Front of the First World War',
    'dp-1': 'He graduated from the Belarusian Theater and Art Institute with a degree in dramatic theater and film actor.',
    'dp-2': 'Graduated from the Belarusian Theater and Art Institute with a degree in drama director.',
    'dp-3': 'Became the director of the Belarusian Theater for Young Spectators',
    'dp-4': 'Dropped from the post of Director of the Belarusian Theater of the Young Spectator',
    'dp-5': 'Head of the Department of the Ministry responsible for the work of the theaters',
    'dp-6': 'He gave the post of head of the department of the ministry in charge of the work of theaters in the country',
    'mr-1': "founded the Rondstudiya Children's Theater.",
    'mr-2': "opened a children's summer creative base 'Harmony' in the Grodno region. Started a project to hold international festivals of children's theaters “Step into the sky” in Minsk.",
    'mr-3': 'graduated from director courses in Moscow.',
    'mr-4': "founded the children's film school 'Cinema' at the Union of Cinematographers of the Republic of Belarus.",
    'mr-5': "opened a children's theater and cinema center in Minsk, uniting all structures into one..",
    'sm-1': 'He graduated from the Opera and Drama Studio. K. Stanislavsky in Moscow (now Stanislavsky Electrotheatre).',
    'sm-2': 'became the director of the Kiev Opera and Ballet Theater. T. Shevchenko',
    'sm-3': 'He gave the post of director of the Kiev Opera and Ballet Theater. T. Shevchenko. He became the chief director of the Chelyabinsk Theater of Opera and Ballet. M. Glinka.',
    'sm-4': 'He gave the post of chief director of the Chelyabinsk Opera and Ballet Theater. M. Glinka. He became the chief director of the Odessa Opera and Ballet Theater.',
    'sm-5': 'He gave the post of chief director of the Odessa Opera and Ballet Theater. He became artistic director and chief director of the Belarusian Bolshoi Opera and Ballet Theater in Minsk.',
    'sm-6': 'He gave the post of artistic director and chief director of the Belarusian Bolshoi Opera and Ballet Theater in Minsk. He became the chief director of the Lviv Opera Theater. I. Franko (now named after S. A. Krushelnytska).',
    'sm-7': 'gave the post of chief director of the Lviv Opera Theater. I. Franko. He became the chief director of the Kiev Opera and Ballet Theater. T. Shevchenko.',
    'title-search': 'The Directors of the theatre of Belarus',
    'title-search-form': 'Search',
    'first-director': 'Aleksandrovskaya Larisa Pompeevna',
    'second-director': 'Buynitsky Ignat Terentyevich',
    'third-director': 'Dopkyunas Vadim Vyacheslavovich',
    'fourth-director': 'Markova Irina Vasilyevna',
    'fifth-director': 'Smolich Dmitry Nikolaevich',
    'first-director-born': 'b.p. с. Minsk',
    'second-director-born': 'b.p. h. Polivach',
    'third-director-born': 'b.p. с. Anadyr',
    'fourth-director-born': 'b.p. с. Minsk',
    'fifth-director-born': 'b.p. с. St. Petersburg',
    'years-of-life': '',
    'creative-activity': '',
    performances: '',
    'zaporozhets-danube': '',
    'silent-don': '',
    'scary-yard': '',
    mermaid: '',
    mazepa: '',
    aida: '',
    'girl-polesia': '',
    'boris-godunov': '',
    traviata: '',
    troubadour: '',
    'nadezhda-durova': '',
    'mihass-podgorny': '',
    'clear-dawn': '',
    'queen-spades': '',
    'aleksandrovskaya-desc': '',
    'main-page': 'Main page',
    'search-page': 'List of actors',
    'project-authors': 'Project authors',
  },
  ru: {
    firstName: 'имя',
    lastName: 'фамилия',
    patronymic: 'отчество',
    desc: 'Описание',
    'al-1': 'Начала выступать как певица в труппе театра Главполитпросвета Западного фронта.',
    'al-2': 'Начало обучения в Минском музыкальном техникуме.',
    'al-3': 'Исполняла белорусские народные песни на Международной музыкальной выставке во Франкфурте-на-Майне (Германия).',
    'al-4': 'Конец обучения в Минском музыкальном техникуме.Обучение в специальном оперном классе.',
    'al-5': 'Солистка Белорусского театра оперы и балета в Минске. Исполняла как сопрановые, так и меццо-сопрановые партии.',
    'al-6': 'Старт карьеры главного режиссёра в Белорусском театре оперы и балета.',
    'al-7': 'Конец карьеры главного режиссёра в Белорусском театре оперы и балета.',
    'bn-1': 'вместе с дочерьми Вандой и Еленой, а также со своими близкими друзьями создал в фольварке Поливачи любительскую труппу.',
    'bn-2': 'на основе любительской группы была сформирована постоянная группа и начаты продолжительные гастроли по Беларуси.',
    'bn-3': 'организовал Прозорокское белорусское кредитное общество, в котором каждый крестьянин под небольшой процент мог получить заём.',
    'bn-4': 'начал принимать активное участие в деятельности виленского общества «В помощь фронту»',
    'bn-5': 'закончил принимать активное участие в деятельности виленского общества «В помощь фронту»',
    'bn-6': 'отправился на Западный фронт Первой мировой войны',
    'dp-1': 'Окончил Белорусский театрально-художественный институт по специальности «актер драматического театра и кино»',
    'dp-2': 'Окончил Белорусский театрально-художественный институт по специальности режиссёр драмы',
    'dp-3': 'Стал директором Белорусского театра юного зрителя',
    'dp-4': 'Сошел с поста Директора Белорусского театра юного зрителя',
    'dp-5': 'Руководитель подразделения министерства, курирующего работу театров страны',
    'dp-6': 'Отдал пост руководителя подразделения министерства, курирующего работу театров страны',
    'mr-1': 'основала детский театр «Рондстудия».',
    'mr-2': 'открыла детскую летнюю творческую базу «Гармония» в Гродненской области. Начала проект проведения международных фестивалей детских театров «Шаг в небо» в г. Минске.',
    'mr-3': 'окончила режиссёрские курсы в Москве.',
    'mr-4': 'основала детскую киношколу «Синема» при союзе кинематографистов Республики Беларусь.',
    'mr-5': 'открыла в г. Минске Детский центр театра и кино, объединив все структуры в одно целое.',
    'sm-1': 'окончил оперно-драматическую студию им. К. Станиславского в Москве (ныне Электротеатр Станиславский).',
    'sm-2': 'стал режиссёром Киевского театра оперы и балета им. Т. Шевченко',
    'sm-3': 'отдал пост режиссёра Киевского театра оперы и балета им. Т. Шевченко. Стал главным режиссёром Челябинского театра оперы и балета им. М. Глинки.',
    'sm-4': 'отдал пост главным режиссёром Челябинского театра оперы и балета им. М. Глинки. Стал главным режиссёром Одесского театра оперы и балета.',
    'sm-5': 'отдал пост главного режиссёра Одесского театра оперы и балета. Стал художественным руководителем и главным режиссёром Белорусского Большого театра оперы и балета в Минске.',
    'sm-6': 'отдал пост художественного руководителя и главного режиссёра Белорусского Большого театра оперы и балета в Минске. Стал главным режиссёром Львовского оперного театра им. И. Франко (ныне — имени С. А. Крушельницкой).',
    'sm-7': 'отдал пост главного режиссёра Львовского оперного театра им. И. Франко. Стал главным режиссёром Киевского театра оперы и балета им. Т. Шевченко.',
    'title-search': 'Режиссеры театра Беларуси',
    'title-search-form': 'Поиск',
    'first-director': 'Александровская Лариса Помпеевна',
    'second-director': 'Буйницкий Игнат Терентьевич',
    'third-director': 'Допкюнас Вадим Вячеславович',
    'fourth-director': 'Маркова Ирина Васильевна',
    'fifth-director': 'Смолич Дмитрий Николаевич',
    'first-director-born': 'м.р. г. Минск',
    'second-director-born': 'м.р. у. Поливачи',
    'third-director-born': 'м.р. г. Анадырь',
    'fourth-director-born': 'м.р. г. Минск',
    'fifth-director-born': 'м.р. г. Санкт-Петербург',
    'years-of-life': '',
    'creative-activity': 'Творческая деятельность',
    performances: 'Постановки спектаклей',
    'zaporozhets-danube': 'апорожец за Дунаем» С. С. Гулак-Артемовского',
    'silent-don': '«Тихий Дон» И.И.Дзержинского',
    'scary-yard': '«Страшный двор» С. Монюшко',
    mermaid: '«Русалка» А. С. Даргомыжского',
    mazepa: '«Мазепа» П. И. Чайковского',
    aida: '«Аида» Дж.Верди',
    'girl-polesia': '«Девушка из Полесья» Е. К. Тикоцкого',
    'boris-godunov': '«Борис Годунов» М.П.Мусоргского',
    traviata: '«Травиата» Дж.Верди',
    troubadour: '«Трубадур» Дж. Верди',
    'nadezhda-durova': '«Надежда Дурова» А.В.Богатырёва',
    'mihass-podgorny': '«Михась Подгорный» Е.К.Тикоцкого',
    'clear-dawn': '«Ясный рассвет (белор.)русск.» А. Е. Туренкова',
    'queen-spades': '«Пиковая дама» П. И. Чайковского.',
    'aleksandrovskaya-desc': 'Белорусская советская оперная певица(сопрано), режиссёр, публицист и общественный деятель.',
    'main-page': 'Главная',
    'search-page': 'Список деятелей',
    'project-authors': 'Авторы проекта',
  },
  by: {
    firstName: 'імя',
    lastName: 'прозвішча',
    patronymic: 'імя па бацьку',
    desc: 'Апісанне',
    'al-1': 'пачала выступаць як спявачка ў трупе тэатра Главполитпросвета Заходняга фронту.',
    'al-2': 'Пачатак навучання ў Мінскім музычным тэхнікуме.',
    'al-3': 'Выконвала беларускія народныя песні на Міжнароднай музычнай выстаўцы ў Франкфурце-на-Майне (Германія).',
    'al-4': 'канец навучання ў Мінскім музычным тэхнікуме.Навучанне ў спецыяльным оперным класе.',
    'al-5': 'салістка беларускага тэатра оперы і балета ў Мінску. Выконвала як сапранавыя, так і мецца-сапранавыя партыі.',
    'al-6': "Старт кар'еры галоўнага рэжысёра ў Беларускім тэатры оперы і балета.",
    'al-7': "канец кар'еры галоўнага рэжысёра ў Беларускім тэатры оперы і балета.",
    'bn-1': 'разам з дочкамі Вандай і Аленай, а таксама са сваімі блізкімі сябрамі стварыў у фальварку Палівачы аматарскую трупу.',
    'bn-2': 'на аснове аматарскай групы была сфарміравана пастаянная група і пачаты працяглыя гастролі па Беларусі.',
    'bn-3': 'арганізаваў Празароцкае беларускае крэдытнае таварыства, у якім кожны селянін пад невялікі адсотак мог атрымаць пазыку.',
    'bn-4': 'пачаў прымаць актыўны ўдзел у дзейнасці віленскага таварыства «У дапамогу фронту»',
    'bn-5': 'скончыў прымаць актыўны ўдзел у дзейнасці віленскага таварыства «У дапамогу фронту»',
    'bn-6': 'адправіўся на Заходні фронт Першай сусветнай вайны',
    'dp-1': ' Скончыў Беларускі тэатральна-мастацкі інстытут па спецыяльнасці «актор драматычнага тэатра і кіно»',
    'dp-2': 'Скончыў Беларускі тэатральна-мастацкі інстытут па спецыяльнасці рэжысёр драмы',
    'dp-3': ' Стаў дырэктарам Беларускага тэатра юнага гледача',
    'dp-4': ' Сышоў з паста Дырэктара Беларускага тэатра юнага гледача',
    'dp-5': 'Кіраўнік падраздзялення міністэрства, што курыруе працу тэатраў краіны',
    'dp-6': 'Аддаў пост кіраўніка падраздзялення міністэрства, што курыруе працу тэатраў краіны',
    'mr-1': "заснавала дзіцячы тэатр 'Рондстудыя'.",
    'mr-2': "адкрыла дзіцячую летнюю творчую базу 'гармонія' ў Гродзенскай вобласці. Пачала праект правядзення міжнародных фестываляў дзіцячых тэатраў 'крок у неба' ў г.Мінску.",
    'mr-3': ' скончыла рэжысёрскія курсы ў Маскве.',
    'mr-4': "заснавала дзіцячую кінашколу 'Сінема' пры Саюзе кінематаграфістаў Рэспублікі Беларусь.",
    'mr-5': "адкрыла ў г. Мінску дзіцячы цэнтр тэатра і кіно, аб'яднаўшы ўсе структуры ў адно цэлае.",
    'sm-1': 'скончыў оперно-драматычную студыю ім. К. Станіслаўскага ў Маскве (цяпер Электратэатр Станіслаўскі).',
    'sm-2': 'стаў рэжысёрам Кіеўскага тэатра оперы і балета ім. Т. Шаўчэнка',
    'sm-3': 'аддаў пост рэжысёра Кіеўскага тэатра оперы і балета ім. Т. Шаўчэнка. Стаў галоўным рэжысёрам Чалябінскага тэатра оперы і балета ім. М. Глінкі.',
    'sm-4': 'аддаў пост галоўным рэжысёрам Чалябінскага тэатра оперы і балета ім. М. Глінкі. Стаў галоўным рэжысёрам Адэскага тэатра оперы і балета.',
    'sm-5': 'аддаў пост галоўнага рэжысёра Адэскага тэатра оперы і балета. Стаў мастацкім кіраўніком і галоўным рэжысёрам Беларускага Вялікага тэатра оперы і балета ў Мінску.',
    'sm-6': 'аддаў пост мастацкага кіраўніка і галоўнага рэжысёра Беларускага Вялікага тэатра оперы і балета ў Мінску. Стаў галоўным рэжысёрам Ільвоўскага опернага тэатра ім. І. Франка (цяпер — імя С. А. Крушальніцкай).',
    'sm-7': 'аддаў пост галоўнага рэжысёра Львоўскага опернага тэатра ім. І. Франка. Стаў галоўным рэжысёрам Кіеўскага тэатра оперы і балета ім. Т. Шаўчэнка.',
    'title-search': 'Рэжысёры тэатра Беларусі',
    'title-search-form': 'Поиск',
    'first-director': 'Александроўская Ларыса Пампееўна',
    'second-director': 'Буйніцкі Ігнат Цярэнцьевіч',
    'third-director': 'Допкюнас Вадзім Вячаслававіч',
    'fourth-director': 'Маркава Ірына Васільеўна',
    'fifth-director': 'Дзмітрый Мікалаевіч Смоліч',
    'first-director-born': 'м.н. г. Менск',
    'second-director-born': 'м.н. ф. Палівачы',
    'third-director-born': 'м.н. г. Анадыр',
    'fourth-director-born': 'м.н. г. Менск',
    'fifth-director-born': 'м.н. Санкт-Пецярбург',
    'years-of-life': '',
    'creative-activity': '',
    performances: '',
    'zaporozhets-danube': '',
    'silent-don': '',
    'scary-yard': '',
    mermaid: '',
    mazepa: '',
    aida: '',
    'girl-polesia': '',
    'boris-godunov': '',
    traviata: '',
    troubadour: '',
    'nadezhda-durova': '',
    'mihass-podgorny': '',
    'clear-dawn': '',
    'queen-spades': '',
    'aleksandrovskaya-desc': '',
    'main-page': 'Галоўная',
    'search-page': 'Cпіс дзеячаў',
    'project-authors': 'Aўтары праекта',
  },
};

export default language;
