const language = {
  en: {
    firstName: 'first',
    lastName: 'last',
    patronymic: 'patr',
    desc: 'Description',
    'al-1': 'She began to act as a singer in the troupe of the Main Front Political Theater of the Western Front.',
    'al-2': 'Start learning in the Minsk Music College.',
    'al-3': 'She performed Belarusian folk songs at the International Music Fair in Frankfurt am Main (Germany).',
    'al-4': 'The end of training in the Minsk musical technical school. Training in a special opera class.',
    'al-5': 'Soloist of the Belarusian Opera and Ballet Theater in Minsk. She performed both soprano and mezzo-soprano parts.',
    'al-6': 'The start of the career of the main director at the Belarusian Opera and Ballet Theater.',
    'al-7': 'The end of the career of the main director in the Belarusian Theater of Opera and Ballet.',
    'bn-1': 'together with his daughters Vanda and Elena, as well as with his close friends, he created an amateur troupe in the Polivachi farm.',
    'bn-2': 'on the basis of the amateur group, a permanent group was formed and a long tour began in Belarus.',
    'bn-3': 'organized the Prozoroki Belarusian Credit Society, in which every peasant could receive a loan at a small percentage.',
    'bn-4': "began to take an active part in the activities of the Vilnius society 'To help the front' ",
    'bn-5': "finished taking an active part in the activities of the Vilnius society 'To help the front' ",
    'bn-6': 'went to the Western Front of the First World War',
    'dp-1': 'He graduated from the Belarusian Theater and Art Institute with a degree in dramatic theater and film actor.',
    'dp-2': 'Graduated from the Belarusian Theater and Art Institute with a degree in drama director.',
    'dp-3': 'Became the director of the Belarusian Theater for Young Spectators',
    'dp-4': 'Dropped from the post of Director of the Belarusian Theater of the Young Spectator',
    'dp-5': 'Head of the Department of the Ministry responsible for the work of the theaters',
    'dp-6': 'He gave the post of head of the department of the ministry in charge of the work of theaters in the country',
    'mr-1': "founded the Rondstudiya Children's Theater.",
    'mr-2': "opened a children's summer creative base 'Harmony' in the Grodno region. Started a project to hold international festivals of children's theaters “Step into the sky” in Minsk.",
    'mr-3': 'graduated from director courses in Moscow.',
    'mr-4': "founded the children's film school 'Cinema' at the Union of Cinematographers of the Republic of Belarus.",
    'mr-5': "opened a children's theater and cinema center in Minsk, uniting all structures into one..",
    'sm-1': 'He graduated from the Opera and Drama Studio. K. Stanislavsky in Moscow (now Stanislavsky Electrotheatre).',
    'sm-2': 'became the director of the Kiev Opera and Ballet Theater. T. Shevchenko',
    'sm-3': 'He gave the post of director of the Kiev Opera and Ballet Theater. T. Shevchenko. He became the chief director of the Chelyabinsk Theater of Opera and Ballet. M. Glinka.',
    'sm-4': 'He gave the post of chief director of the Chelyabinsk Opera and Ballet Theater. M. Glinka. He became the chief director of the Odessa Opera and Ballet Theater.',
    'sm-5': 'He gave the post of chief director of the Odessa Opera and Ballet Theater. He became artistic director and chief director of the Belarusian Bolshoi Opera and Ballet Theater in Minsk.',
    'sm-6': 'He gave the post of artistic director and chief director of the Belarusian Bolshoi Opera and Ballet Theater in Minsk. He became the chief director of the Lviv Opera Theater. I. Franko (now named after S. A. Krushelnytska).',
    'sm-7': 'gave the post of chief director of the Lviv Opera Theater. I. Franko. He became the chief director of the Kiev Opera and Ballet Theater. T. Shevchenko.',
    'title-search': 'The Directors of the theatre of Belarus',
    'title-search-form': 'Search',
    'first-director': 'Aleksandrovskaya Larisa Pompeevna',
    'second-director': 'Buynitsky Ignat Terentyevich',
    'third-director': 'Dopkyunas Vadim Vyacheslavovich',
    'fourth-director': 'Markova Irina Vasilyevna',
    'fifth-director': 'Smolich Dmitry Nikolaevich',
    'first-director-born': 'b.p. с. Minsk',
    'second-director-born': 'b.p. h. Polivach',
    'third-director-born': 'b.p. с. Anadyr',
    'fourth-director-born': 'b.p. с. Minsk',
    'fifth-director-born': 'b.p. с. St. Petersburg',
    'years-of-life': 'Years of life:',
    'creative-activity': 'Creative activity',
    'description-site': 'Belarusian theater history goes back centuries. The Belarusian professional theater has developed from ancient folk rituals, the creative work of strolling musicians, the court troupes of the Belarusian magnates, the activity of amateur groups at the turn of the 19th and 20th centuries. The theater life of Belarus is full of vivid festival events. The scene masters come to Belarus to present their best works for review by theatre workers and spectators. This portal is dedicated to the culture of Belarus, namely the directors of the Theater of Belarus. On the page list of figures you can find information about the directors, their work and the creative stages of life. This website is dedicated to the culture of Belarus, namely to the directors of the Belarus theater. With the search page you can find information about the directors, their works and the creative stages of life.',
    videogallery: 'Video about the director',
    performances: 'Statements of performances',
    'al-per-1': '"Zaporozhets beyond Danube" by S.S. Gulak-Artemovsky',
    'al-per-2': '"Quiet Don" by I.I. Dzerzhinsky',
    'al-per-3': '"Terrible yard" by S. Monyushko',
    'al-per-4': '"Mermaid" by A.S. Dargomyzhsky',
    'al-per-5': '"Mazepa" by P. I. Tchaikovsky',
    'al-per-6': '"Aida" by G. Verdi',
    'al-per-7': '"Girl from Polesie" by E. K. Tikotsky',
    'al-per-8': '"Boris Godunov" by M. P. Musorgsky',
    'al-per-9': '"Traviata" by G. Verdi',
    'al-per-10': '"Troubadour" by G. Verdi',
    'al-per-11': '"Nadezhda Durova" by A.V. Bogatyryov',
    'al-per-12': '"Mikhas Podgorny" by E.K. Tikotsky',
    'al-per-13': '"Clear dawn" by A.E. Turenkova',
    'al-per-14': '"Queen of spades" by P.I. Tchaikovsky',
    'al-desc': 'Belarusian Soviet opera singer (soprano), director, publicist and public figure.',
    'main-page': 'Main page',
    'search-page': 'List of actors',
    'project-authors': 'Project authors',
    'dapkiunas-desc': 'Belarusian theatrical figure and organizer of theatrical affairs, the author of the first production in the professional theater of the play by Alexander Vampilov.',
    'dp-per-1': 'Farewell to June',
    'dp-per-2': 'Time is not waiting',
    'dp-per-3': 'Leaving nature',
    'bn-desc': 'Belarusian actor, director, theatrical figure, founder of the first professional national Belarusian theatre.',
    'bn-per-1': 'By revision',
    'bn-per-2': 'In the winter evening',
    'sm-desc': 'Soviet Opera Director, people\'s artist of the USSR.',
    'sm-per-1': '"La Traviata"',
    'sm-per-2': '"The Queen of Spades"',
    'sm-per-3': '"Prince Igor"',
    'sm-per-4': '"Keto and Kote"',
    'director-of-the-day': 'Director of the day',
    'mr-decs': 'Teacher, director, artistic director of the Rond theater, director of the Cinema film school at the Children\'s Center for Theater and Cinema.',
    'selected-filmography': 'Selected filmography',
    'mr-per-1': 'Galatea Megapolis',
    'mr-per-2': 'Dream',
    'mr-per-3': 'Music',
    'mr-per-4': 'Happy rain',
    'mr-per-5': 'Road to angel',
    'mr-per-6': 'Tarot card',
    'mr-per-7': 'The first love',
    'mr-per-8': 'Small lamplighter',
    'mr-per-9': 'Fade out',
    'mr-per-10': 'Awakening, Protection',
    'mr-per-11': 'Study on the topic of cinema',
    'mr-per-12': 'Random fairy',
    'mr-per-13': 'Echo',
    'mr-per-14': 'Notes of an ordinary person',
    'mr-per-15': 'Can I sing?',
    'mr-per-16': 'Unprofitable',
  },
  ru: {
    firstName: 'имя',
    lastName: 'фамилия',
    patronymic: 'отчество',
    desc: 'Описание',
    'al-1': 'Начала выступать как певица в труппе театра Главполитпросвета Западного фронта.',
    'al-2': 'Начало обучения в Минском музыкальном техникуме.',
    'al-3': 'Исполняла белорусские народные песни на Международной музыкальной выставке во Франкфурте-на-Майне (Германия).',
    'al-4': 'Конец обучения в Минском музыкальном техникуме.Обучение в специальном оперном классе.',
    'al-5': 'Солистка Белорусского театра оперы и балета в Минске. Исполняла как сопрановые, так и меццо-сопрановые партии.',
    'al-6': 'Старт карьеры главного режиссёра в Белорусском театре оперы и балета.',
    'al-7': 'Конец карьеры главного режиссёра в Белорусском театре оперы и балета.',
    'bn-1': 'вместе с дочерьми Вандой и Еленой, а также со своими близкими друзьями создал в фольварке Поливачи любительскую труппу.',
    'bn-2': 'на основе любительской группы была сформирована постоянная группа и начаты продолжительные гастроли по Беларуси.',
    'bn-3': 'организовал Прозорокское белорусское кредитное общество, в котором каждый крестьянин под небольшой процент мог получить заём.',
    'bn-4': 'начал принимать активное участие в деятельности виленского общества «В помощь фронту»',
    'bn-5': 'закончил принимать активное участие в деятельности виленского общества «В помощь фронту»',
    'bn-6': 'отправился на Западный фронт Первой мировой войны',
    'dp-1': 'Окончил Белорусский театрально-художественный институт по специальности «актер драматического театра и кино»',
    'dp-2': 'Окончил Белорусский театрально-художественный институт по специальности режиссёр драмы',
    'dp-3': 'Стал директором Белорусского театра юного зрителя',
    'dp-4': 'Сошел с поста Директора Белорусского театра юного зрителя',
    'dp-5': 'Руководитель подразделения министерства, курирующего работу театров страны',
    'dp-6': 'Отдал пост руководителя подразделения министерства, курирующего работу театров страны',
    'mr-1': 'основала детский театр «Рондстудия».',
    'mr-2': 'открыла детскую летнюю творческую базу «Гармония» в Гродненской области. Начала проект проведения международных фестивалей детских театров «Шаг в небо» в г. Минске.',
    'mr-3': 'окончила режиссёрские курсы в Москве.',
    'mr-4': 'основала детскую киношколу «Синема» при союзе кинематографистов Республики Беларусь.',
    'mr-5': 'открыла в г. Минске Детский центр театра и кино, объединив все структуры в одно целое.',
    'sm-1': 'окончил оперно-драматическую студию им. К. Станиславского в Москве (ныне Электротеатр Станиславский).',
    'sm-2': 'стал режиссёром Киевского театра оперы и балета им. Т. Шевченко',
    'sm-3': 'отдал пост режиссёра Киевского театра оперы и балета им. Т. Шевченко. Стал главным режиссёром Челябинского театра оперы и балета им. М. Глинки.',
    'sm-4': 'отдал пост главным режиссёром Челябинского театра оперы и балета им. М. Глинки. Стал главным режиссёром Одесского театра оперы и балета.',
    'sm-5': 'отдал пост главного режиссёра Одесского театра оперы и балета. Стал художественным руководителем и главным режиссёром Белорусского Большого театра оперы и балета в Минске.',
    'sm-6': 'отдал пост художественного руководителя и главного режиссёра Белорусского Большого театра оперы и балета в Минске. Стал главным режиссёром Львовского оперного театра им. И. Франко (ныне — имени С. А. Крушельницкой).',
    'sm-7': 'отдал пост главного режиссёра Львовского оперного театра им. И. Франко. Стал главным режиссёром Киевского театра оперы и балета им. Т. Шевченко.',
    'title-search': 'Режиссеры театра Беларуси',
    'title-search-form': 'Поиск',
    'first-director': 'Александровская Лариса Помпеевна',
    'second-director': 'Буйницкий Игнат Терентьевич',
    'third-director': 'Допкюнас Вадим Вячеславович',
    'fourth-director': 'Маркова Ирина Васильевна',
    'fifth-director': 'Смолич Дмитрий Николаевич',
    'first-director-born': 'м.р. г. Минск',
    'second-director-born': 'м.р. у. Поливачи',
    'third-director-born': 'м.р. г. Анадырь',
    'fourth-director-born': 'м.р. г. Минск',
    'fifth-director-born': 'м.р. г. Санкт-Петербург',
    'years-of-life': 'Годы жизни:',
    'creative-activity': 'Творческая деятельность',
    videogallery: 'Видео о режиссере',
    performances: 'Постановки спектаклей',
    'al-per-1': '«Запорожец за Дунаем» С. С. Гулак-Артемовского',
    'al-per-2': '«Тихий Дон» И.И.Дзержинского',
    'al-per-3': '«Страшный двор» С. Монюшко',
    'al-per-4': '«Русалка» А. С. Даргомыжского',
    'al-per-5': '«Мазепа» П. И. Чайковского',
    'al-per-6': '«Аида» Дж.Верди',
    'al-per-7': '«Девушка из Полесья» Е. К. Тикоцкого',
    'al-per-8': '«Борис Годунов» М.П.Мусоргского',
    'al-per-9': '«Травиата» Дж.Верди',
    'al-per-10': '«Трубадур» Дж. Верди',
    'al-per-11': '«Надежда Дурова» А.В.Богатырёва',
    'al-per-12': '«Михась Подгорный» Е.К.Тикоцкого',
    'al-per-13': '«Ясный рассвет (белор.)русск.» А. Е. Туренкова',
    'al-per-14': '«Пиковая дама» П. И. Чайковского.',
    'al-desc': 'Белорусская советская оперная певица(сопрано), режиссёр, публицист и общественный деятель.',
    'main-page': 'Главная',
    'search-page': 'Список деятелей',
    'project-authors': 'Авторы проекта',
    'dapkiunas-desc': 'белорусский театральный деятель и организатор театрального дела, автор первой постановки в профессиональном театре пьесы Александра Вампилова.',
    'dp-per-1': '«Прощание в июне»',
    'dp-per-2': '«Время-не-ждёт»',
    'dp-per-3': '«Уходящая натура»',
    'bn-desc': 'Белорусский актёр, режиссёр, театральный деятель, основатель первого профессионального национального белорусского театра.',
    'bn-per-1': 'По ревиззии',
    'bn-per-2': 'В зимний вечер',
    'sm-desc': 'Cоветский оперный режиссёр, народный артист СССР.',
    'sm-per-1': '«Травиата»',
    'sm-per-2': '«Пиковая дама»',
    'sm-per-3': '«Князь Игорь»',
    'sm-per-4': '«Кето и Котэ»',
    'description-site': 'Белорусская театральная история насчитывает не одно столетие. Белорусский профессиональный театр развился из древних народных обрядов, творчества бродячих музыкантов, придворных трупп белорусских магнатов, деятельности любительских коллективов рубежа XIX–XX веков. Театральная жизнь Беларуси насыщена яркими фестивальными событиями. Мастера сцены приезжают в Беларусь, чтобы представить на суд театральных деятелей и зрителей свои лучшие работы. Данный портал посвящен культуре Беларуси, а именно режиссерам театра Беларуси. На странице список деятелей вы сможете найти информацию о режиссерах, их работах и творческих этапах жизни.',
    'director-of-the-day': 'Режиссер дня',
    'mr-decs': 'Педагог, режиссёр, художественный руководитель театра «Ронд», директор киношколы «Синема», Детского центра театра и кино.',
    'selected-filmography': 'Избранная фильмография',
    'mr-per-1': 'Галатея Мегаполиса',
    'mr-per-2': 'Мечтой',
    'mr-per-3': 'Музыка',
    'mr-per-4': 'Счастливый дождь',
    'mr-per-5': 'Дорога к ангелу',
    'mr-per-6': 'Карта Таро',
    'mr-per-7': 'Первая любовь',
    'mr-per-8': 'Маленький фонарщик',
    'mr-per-9': 'Исчезновение звука',
    'mr-per-10': 'Пробуждение, Защита',
    'mr-per-11': 'Этюд на тему Кино',
    'mr-per-12': 'Случайная фея',
    'mr-per-13': 'Эхо',
    'mr-per-14': 'Записки заурядной личности',
    'mr-per-15': 'Можно я спою?',
    'mr-per-16': 'Непутевые',
  },
  by: {
    firstName: 'імя',
    lastName: 'прозвішча',
    patronymic: 'імя па бацьку',
    desc: 'Апісанне',
    'al-1': 'пачала выступаць як спявачка ў трупе тэатра Главполитпросвета Заходняга фронту.',
    'al-2': 'Пачатак навучання ў Мінскім музычным тэхнікуме.',
    'al-3': 'Выконвала беларускія народныя песні на Міжнароднай музычнай выстаўцы ў Франкфурце-на-Майне (Германія).',
    'al-4': 'канец навучання ў Мінскім музычным тэхнікуме.Навучанне ў спецыяльным оперным класе.',
    'al-5': 'салістка беларускага тэатра оперы і балета ў Мінску. Выконвала як сапранавыя, так і мецца-сапранавыя партыі.',
    'al-6': "Старт кар'еры галоўнага рэжысёра ў Беларускім тэатры оперы і балета.",
    'al-7': "канец кар'еры галоўнага рэжысёра ў Беларускім тэатры оперы і балета.",
    'bn-1': 'разам з дочкамі Вандай і Аленай, а таксама са сваімі блізкімі сябрамі стварыў у фальварку Палівачы аматарскую трупу.',
    'bn-2': 'на аснове аматарскай групы была сфарміравана пастаянная група і пачаты працяглыя гастролі па Беларусі.',
    'bn-3': 'арганізаваў Празароцкае беларускае крэдытнае таварыства, у якім кожны селянін пад невялікі адсотак мог атрымаць пазыку.',
    'bn-4': 'пачаў прымаць актыўны ўдзел у дзейнасці віленскага таварыства «У дапамогу фронту»',
    'bn-5': 'скончыў прымаць актыўны ўдзел у дзейнасці віленскага таварыства «У дапамогу фронту»',
    'bn-6': 'адправіўся на Заходні фронт Першай сусветнай вайны',
    'dp-1': ' Скончыў Беларускі тэатральна-мастацкі інстытут па спецыяльнасці «актор драматычнага тэатра і кіно»',
    'dp-2': 'Скончыў Беларускі тэатральна-мастацкі інстытут па спецыяльнасці рэжысёр драмы',
    'dp-3': ' Стаў дырэктарам Беларускага тэатра юнага гледача',
    'dp-4': ' Сышоў з паста Дырэктара Беларускага тэатра юнага гледача',
    'dp-5': 'Кіраўнік падраздзялення міністэрства, што курыруе працу тэатраў краіны',
    'dp-6': 'Аддаў пост кіраўніка падраздзялення міністэрства, што курыруе працу тэатраў краіны',
    'mr-1': "заснавала дзіцячы тэатр 'Рондстудыя'.",
    'mr-2': "адкрыла дзіцячую летнюю творчую базу 'гармонія' ў Гродзенскай вобласці. Пачала праект правядзення міжнародных фестываляў дзіцячых тэатраў 'крок у неба' ў г.Мінску.",
    'mr-3': ' скончыла рэжысёрскія курсы ў Маскве.',
    'mr-4': "заснавала дзіцячую кінашколу 'Сінема' пры Саюзе кінематаграфістаў Рэспублікі Беларусь.",
    'mr-5': "адкрыла ў г. Мінску дзіцячы цэнтр тэатра і кіно, аб'яднаўшы ўсе структуры ў адно цэлае.",
    'sm-1': 'скончыў оперно-драматычную студыю ім. К. Станіслаўскага ў Маскве (цяпер Электратэатр Станіслаўскі).',
    'sm-2': 'стаў рэжысёрам Кіеўскага тэатра оперы і балета ім. Т. Шаўчэнка',
    'sm-3': 'аддаў пост рэжысёра Кіеўскага тэатра оперы і балета ім. Т. Шаўчэнка. Стаў галоўным рэжысёрам Чалябінскага тэатра оперы і балета ім. М. Глінкі.',
    'sm-4': 'аддаў пост галоўным рэжысёрам Чалябінскага тэатра оперы і балета ім. М. Глінкі. Стаў галоўным рэжысёрам Адэскага тэатра оперы і балета.',
    'sm-5': 'аддаў пост галоўнага рэжысёра Адэскага тэатра оперы і балета. Стаў мастацкім кіраўніком і галоўным рэжысёрам Беларускага Вялікага тэатра оперы і балета ў Мінску.',
    'sm-6': 'аддаў пост мастацкага кіраўніка і галоўнага рэжысёра Беларускага Вялікага тэатра оперы і балета ў Мінску. Стаў галоўным рэжысёрам Ільвоўскага опернага тэатра ім. І. Франка (цяпер — імя С. А. Крушальніцкай).',
    'sm-7': 'аддаў пост галоўнага рэжысёра Львоўскага опернага тэатра ім. І. Франка. Стаў галоўным рэжысёрам Кіеўскага тэатра оперы і балета ім. Т. Шаўчэнка.',
    'title-search': 'Рэжысёры тэатра Беларусі',
    'title-search-form': 'Поиск',
    'first-director': 'Александроўская Ларыса Пампееўна',
    'second-director': 'Буйніцкі Ігнат Цярэнцьевіч',
    'third-director': 'Допкюнас Вадзім Вячаслававіч',
    'fourth-director': 'Маркава Ірына Васільеўна',
    'fifth-director': 'Дзмітрый Мікалаевіч Смоліч',
    'first-director-born': 'м.н. г. Менск',
    'second-director-born': 'м.н. ф. Палівачы',
    'third-director-born': 'м.н. г. Анадыр',
    'fourth-director-born': 'м.н. г. Менск',
    'fifth-director-born': 'м.н. Санкт-Пецярбург',
    'years-of-life': 'Гады жыцця:',
    'creative-activity': 'Творчая дзейнасць',
    videogallery: 'Відэа пра рэжысёра',
    performances: 'Пастаноўкі спектакляў',
    'al-per-1': '"Запарожац за Дунаем" С. С. Гулак-Арцёмаўскі',
    'al-per-2': '"Ціхі Дон" І. І. Дзяржынскага',
    'al-per-3': '"Страшны двор" С. Манюшкі',
    'al-per-4': '"Русалка" А. С. Даргамыжскага',
    'al-per-5': '"Мазепа" П. І. Чайкоўскага',
    'al-per-6': '"Аіда" Дж. Вердзі',
    'al-per-7': '"Дзяўчына з Палесся" Я. К. Цікоцкага',
    'al-per-8': '"Барыс Гадуноў" М. П. Мусаргскага',
    'al-per-9': '"Травіята" Дж. Вердзі',
    'al-per-10': '"Трубадур" Дж. Вердзі',
    'al-per-11': '"Надзея Дурава" А. В. Багатырова',
    'al-per-12': '"Міхась Падгорны" Я. К. Цікоцкага',
    'al-per-13': '"Ясны світанак" А. Е. Туренкова',
    'al-per-14': '"Пікавая дама" П. І. Чайкоўскага',
    'al-desc': 'Беларуская Савецкая оперная спявачка (сапрана), рэжысёр, публіцыст і грамадскі дзеяч.',
    'main-page': 'Галоўная',
    'search-page': 'Cпіс дзеячаў',
    'project-authors': 'Aўтары праекта',
    'dapkiunas-desc': 'беларускі тэатральны дзеяч і арганізатар тэатральнай справы, аўтар першай пастаноўкі ў прафесійным тэатры п"есы Аляксандра Вампилова.',
    'dp-per-1': 'Развітанне ў чэрвені',
    'dp-per-2': 'Час-не-чакае',
    'dp-per-3': 'Якая сыходзіць натура',
    'bn-desc': 'Беларускі акцёр, рэжысёр, тэатральны дзеяч, заснавальнік першага прафесійнага нацыянальнага беларускага тэатра.',
    'bn-per-1': 'Па рэвіззіі',
    'bn-per-2': 'У зімовы вечар',
    'sm-desc': 'Савецкі оперны рэжысёр, народны артыст СССР.',
    'sm-per-1': '"Травіята"',
    'sm-per-2': '"Пікавая дама"',
    'sm-per-3': '"Князь Ігар"',
    'sm-per-4': '"Кето і Котэ"',
    'description-site': 'Беларуская тэатральная гісторыя налічвае не адно стагоддзе. Беларускі прафесійны тэатр развіваўся са старажытных народных абрадаў, творчасці вандроўных музыкаў, прыдворных труп беларускіх магнатаў, дзейнасці аматарскіх калектываў рубяжа XIX-XX стагоддзяў. Тэатральнае жыццё Беларусі насычана яркімі фестывальнымі падзеямі. Майстры сцэны прыязджаюць у Беларусь, каб прадставіць на суд тэатральных дзеячаў і гледачоў свае лепшыя работы. Дадзены партал прысвечаны культуры Беларусі, а менавіта рэжысёрам тэатра Беларусі. На старонцы спіс дзеячаў вы зможаце знайсці інфармацыю аб рэжысёраў, іх працах і творчых этапах жыцця.',
    'director-of-the-day': 'Рэжысёр дня',
    'mr-decs': 'Педагог, рэжысёр, мастацкі кіраўнік тэатра «Ронд», дырэктар кінашколы «Сінема», Дзіцячага цэнтра тэатра і кіно.',
    'selected-filmography': 'Aбраная фільмаграфія',
    'mr-per-1': 'Галатэя Mегаполіс',
    'mr-per-2': 'Mарай',
    'mr-per-3': 'Mузыка',
    'mr-per-4': 'Шчаслівы дождж',
    'mr-per-5': 'Дарога да анёла',
    'mr-per-6': 'Карта Таро',
    'mr-per-7': 'Першае каханне',
    'mr-per-8': 'Маленькі ліхтаршчык',
    'mr-per-9': 'Знікненне гуку',
    'mr-per-10': 'Абуджэнне, Абарона',
    'mr-per-11': 'Эцюд на тэму Кіно',
    'mr-per-12': 'Выпадковая фея',
    'mr-per-13': 'Рэха',
    'mr-per-14': 'Запіскі пасрэднай асобы',
    'mr-per-15': 'Можна я паспяваю вам?',
    'mr-per-16': 'Шалапутныя',
  },
};

export default language;
